# -*- coding: utf-8 -*-
"""ransacAnnafiMirza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186TIVr4WDy66aeoCmkWl0SGz_8IdAWnu
"""

#-----------------------------------
# CSC 315 / DSC 615
#   Project 3   RANSAC Circles
#
#   Annafi Mirza
#
#
#-----------------------------------

import numpy as np
import matplotlib.pyplot as plt
import random
import math

pi = 3.14159265358979323846264

#-----------------------------------
# GenPoints   generates a set of random 2D points
#             containing 5 planted circles
#             within a set of uniformly distributed
#             outliers
#
#     Input:   None
#     Output:  xy    [700 2]  numpy array of 700 2d points
#
#-----------------------------------

def GenPoints():

	n_circle = 5
	point_per_circle = 100
	noise_points = 200
	total_points = n_circle*point_per_circle + noise_points
	xy = np.random.uniform((-10.0,-10.0), (10.0,10.0), (total_points,2))

	for c in range(n_circle):

		# Randomly generate a circle
		xpos   = random.uniform(-8.0,8.0)
		ypos   = random.uniform(-8.0,8.0)
		radius = random.uniform(0.5, 2.0)
		spread = random.uniform(0.05,0.2)

		thetas = np.random.uniform(0.0, 2*pi, (point_per_circle,))
		rhos   = radius + np.random.normal(radius,spread,(point_per_circle,))

		circle_xy = np.zeros((point_per_circle,2), dtype='float64')
		circle_xy[:,0] = xpos + rhos*np.cos(thetas)
		circle_xy[:,1] = ypos + rhos*np.sin(thetas)

		# Fill the portion of the numpy array
		sidx = c*point_per_circle
		eidx = (c+1)*point_per_circle
		xy[sidx:eidx] = circle_xy

	for i in range(total_points):
		j = random.randint(i,total_points-1)
		temp = np.array(xy[i])
		xy[i] = xy[j]
		xy[j] = temp

	return xy
# ----------------------------------------

# Drawing a circle on a graph
def drawCircle(xPos, yPos, radius, color="black", linestyle="-"):
 theta = np.linspace(0, 2 * pi, 50)
 x = xPos + radius * np.sin(theta)
 y = yPos + radius * np.cos(theta)
 plt.plot(x, y, color = color, linestyle = linestyle, linewidth = 2)

# Fiting a circle to 3 random points
def fitCircle(xy):
  points = []
  while len(points) < 3:
    randomChoice = random.randint(0, xy.shape[0] - 1)
    points.append(tuple(xy[randomChoice]))
    # If not every random point is unique
    if len(points) != len(set(points)):
     del points[len(points) - 1]
  # Finding the circumcenter by seeing where the midpoint equations intersect
  midpoint1 = ((points[0][0] + points[1][0]) / 2, (points[0][1] + points[1][1]) / 2)
  midpoint2 = ((points[1][0] + points[2][0]) / 2, (points[1][1] + points[2][1]) / 2)
  # Opposite reciprocals to get perpendicular lines
  slope1 = -1 / ((points[1][1] - points[0][1]) / (points[1][0] - points[0][0]))
  slope2 = -1 / ((points[2][1] - points[1][1]) / (points[2][0] - points[1][0]))
  # Solving for x in m1(x - a) + b = m2(x - c) + d
  X = (midpoint1[0] * slope1 - midpoint2[0] * slope2 - midpoint1[1] + midpoint2[1]) / (slope1 - slope2)
  # Solving for y by plugging into one of previous midpoint equations
  Y = slope1 * (X - midpoint1[0]) + midpoint1[1]
  # Solving for radius with distance formula
  radius = math.sqrt((X - points[0][0])**2 + (Y - points[0][1])**2)
  return X, Y, radius

# Calculate points nearby a given circle
def calcNearbyPts(originalXY, x, y, rad, reason=1):
 # Determines how close every point is to fitted circle's perimeter
 distances = np.abs(np.sqrt((originalXY[:,0] - x)**2 + (originalXY[:,1] - y)**2) - rad)
 # Determines which points are close enough
 isClose = (distances < 0.2)
 isCloseUnaltered = isClose
 isClose = isClose.astype('int32')
 # Returns number of points close to fitted circle
 if reason == 1:
  return np.sum(isClose)
 # Returns which points are close and not close if called for
 else:
  return isCloseUnaltered

# Main RANSAC algorithm
def ransac(xy, iterations, reason=1, color="black"):
 # Initialization
 bestX, bestY, bestRadius = 0, 0, 0
 best_pts_nearby = -99990
 for i in range(iterations):
  X, Y, radius = fitCircle(xy)
  pts_nearby = calcNearbyPts(xy, X, Y, radius)
  if pts_nearby > best_pts_nearby:
   best_pts_nearby = pts_nearby
   bestX, bestY, bestRadius = X, Y, radius
  # Exit early if most points are inliers
  if pts_nearby > len(xy) * 0.8:
   break
 # Draws best fitting circle and intervals of nearby points
 drawCircle(bestX, bestY, bestRadius, color)
 drawCircle(bestX, bestY, bestRadius+0.2, color, linestyle="--")
 drawCircle(bestX, bestY, bestRadius-0.2, color, linestyle="--")
 # Returns best fitting circle's center and radius if called for
 if reason == 0:
  return bestX, bestY, bestRadius

# Detect 5 circles in 1 data set
def detectFiveCircles(xy, iterations):
 copy = xy
 colors = ['red', 'orange', 'purple', 'green', 'blue']
 for i in range(5):
  # Finds center and radius of best fitting circle
  bestX, bestY, bestRadius = ransac(copy, iterations, reason=0, color = colors[i])
  # Removing points of previous circle found to avoid same detection
  nearbyPts = calcNearbyPts(copy, bestX, bestY, bestRadius, reason=0)
  copy = copy[~nearbyPts]

n_runs = 5
n_circle = 5

# Calculation for number of iterations needed for high detection rate
success_rate = 0.99 # Chance of detection wanted
outlier_rate = 0.9 # Assumption of rate of outliers per set
points_per_iteration = 3 # 3 random points selected per circle
num_iterations = int((math.log10(1 - success_rate)) / (math.log10(1 - (1 - outlier_rate)**points_per_iteration)))

for run in range(n_runs):
  xy = GenPoints()
  plt.figure(figsize=(8.0,8.0))
  plt.title("Run " + str(run+1))
  plt.scatter(xy[:,0], xy[:,1], c='black')
  detectFiveCircles(xy, num_iterations)
  plt.show()

print('Done!')