# -*- coding: utf-8 -*-
"""vehicleStatsAnnafiMirza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbEeAjLGxzO4p1lsFqKIcFMMUGRVft_p
"""

#
#   Project 2  Automotive
#
#      Annafi Mirza
#
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math

#---------------------------------------------
#---------------------------------------------
# Custom functions go here
#---------------------------------------------
#---------------------------------------------

# CREATING HISTOGRAMS
def createHistogram(originalDict, sortType, titleAddition):
  # If sortType is alphabetical
  if sortType == 0:
    makes = list(originalDict.keys())
    makesSorted = makes.sort()
    makesAlphabetical = {i: originalDict[i] for i in makes}
    makes = list(makesAlphabetical.keys())
    makes.reverse()
    numOfVehicles = list(makesAlphabetical.values())
    numOfVehicles.reverse()
  # If sortType is by number of vehicles
  else:
    vehiclesSorted = dict(sorted(originalDict.items(), key=lambda item: item[1]))
    makes = list(vehiclesSorted.keys())
    makes.reverse()
    numOfVehicles = list(vehiclesSorted.values())
    numOfVehicles.reverse()
  # Marking special brands
  colors = ['black'] * len(makes)
  colors[makes.index("Chevrolet")] = 'orange'
  colors[makes.index("Ford")] = 'blue'
  colors[makes.index("Toyota")] = 'red'
  # Graphing vehicle sort
  fig = plt.figure(figsize=(10,10))
  plt.barh(makes, numOfVehicles, color=colors)
  plt.xlabel("Number of vehicles")
  plt.title("Number of vehicles by make " + titleAddition)
  plt.show()

# CREATING SCATTER PLOTS
def createScatterPlot(df, make, degree):
  # X and Y axes for specified make
  carDetails = df[df['Make'] == make]
  Hp = carDetails['Horsepower']
  Mpg = carDetails['Mpg']
  # Polynomial regression
  coefficients = np.polyfit(Hp, Mpg, degree)
  polynomialFunction = np.poly1d(coefficients)
  polyX = np.linspace(min(Hp), max(Hp), len(Hp))
  polyY = polynomialFunction(polyX)
  # Calculating polynomial MAE
  polyMae = 0
  for i in range(len(Hp)):
    polyMae += abs(Mpg.iloc[i] - polynomialFunction(Hp)[i])
  polyMae /= len(Hp)
  polyMae = round(polyMae, 2)
  # Linear regression
  linearX = piecewise_kde(Hp, Mpg, degree)[0]
  linearY = piecewise_kde(Hp, Mpg, degree)[1]
  # Calculating linear MAE
  linearMae = 0
  for i in range(len(Hp)):
    j = 0
    while j <= len(linearX) - 1:
      if Hp.iloc[i] <= linearX[j]:
        break
      j += 1
    if j == 0:
      linearMae += abs(Mpg.iloc[i] - pointSlope(linearX[j], linearY[j], linearX[j+1], linearY[j+1], Hp.iloc[i]))
    else:
      linearMae += abs(Mpg.iloc[i] - pointSlope(linearX[j], linearY[j], linearX[j-1], linearY[j-1], Hp.iloc[i]))
  linearMae /= len(Hp)
  linearMae = "%.2f" % round(linearMae, 2)
  # Determining color for points
  if make == 'Chevrolet':
    color = 'orange'
  elif make == 'Ford':
    color = 'blue'
  else:
    color = 'red'
  # Graphing Chevrolet
  fig = plt.figure(figsize=(10,7))
  plt.scatter(Hp, Mpg, color=color)
  plt.plot(polyX, polyY, color='grey', linestyle='dashed', label='polynomial fit mae: ' + str(polyMae))
  plt.plot(linearX, linearY, '^', color='black', linestyle='solid', label='piecewise fit mae: ' + str(linearMae))
  plt.legend(loc='upper right')
  plt.xlabel("Hp")
  plt.ylabel("Mpg")
  # Choosing title
  if degree == 1:
    plt.title(make + " Horsepower versus Mpg (" + str(degree) + "st degree)")
  elif degree == 2:
    plt.title(make + " Horsepower versus Mpg (" + str(degree) + "nd degree)")
  elif degree == 3:
    plt.title(make + " Horsepower versus Mpg (" + str(degree) + "rd degree)")
  else:
    plt.title(make + " Horsepower versus Mpg (" + str(degree) + "th degree)")
  plt.show()

# HELPER FUNCTION FOR FINDING LINEAR MAE
def pointSlope(x1, y1, x2, y2, xVal):
  slope = (y2 - y1) / (x2 - x1)
  return slope * (xVal - x1) + y1

#---------------------------
#
# Piecewise Kernel Density Estimation
#
#  inputs:
#      X        list or 1D np-array of data X-coordinates
#      Y        list or 1D np-array of data Y-coordinates
#      npieces  number of line segments to fit to the dataset
#  outputs:
#      return xout,yout
#
#      xout     output x-coordinates of the fitted line segments
#      yout     output y-coordinates of the fitted line segments
#
#---------------------------

def piecewise_kde(X,Y,npiece):
  X = np.array(X)
  Y = np.array(Y)

  # what are x0 and x1
  x0 = np.min(X)
  x1 = np.max(X)

  # what is sigma
  sigma = 0.25 * (x1-x0) / npiece
  root2pi = 2.50662827463

  # What are the points
  npoint = npiece+1
  xout = np.linspace(x0,x1,npoint)

  # Run the gaussian function over each point
  yout = np.zeros((npoint,), dtype='float64')
  for i in range(npoint):
    mu = xout[i]
    weight = 1.0/(sigma*root2pi) * np.exp(-0.5 * (X-mu)*(X-mu)/(sigma*sigma))
    total = np.sum(Y * weight)
    count = np.sum(weight)
    yout[i] = total/count

  return xout,yout

#---------------------------------------------
#---------------------------------------------
# Main code below
#---------------------------------------------
#---------------------------------------------
df = pd.read_csv("cars.csv")

# Cleaning data
dfClean = df[['Mpg', 'Make', 'Horsepower']]

# Counting amount of vehicles per make
vehicleTracker = {}
for i in range(dfClean.shape[0]):
  if dfClean['Make'][i] in vehicleTracker:
    vehicleTracker[dfClean['Make'][i]] = vehicleTracker.get(dfClean['Make'][i]) + 1
  else:
    vehicleTracker[dfClean['Make'][i]] = 1

# Generating histograms
createHistogram(vehicleTracker, 0, "(alphabetical)")
createHistogram(vehicleTracker, 1, "(lowest to highest)")

# Chevrolet scatter plots
for i in range(5):
  createScatterPlot(dfClean, 'Chevrolet', i+1)

# Ford scatter plots
for i in range(5):
  createScatterPlot(dfClean, 'Ford', i+1)

# Toyota scatter plots
for i in range(5):
  createScatterPlot(dfClean, 'Toyota', i+1)